all: equivalent1_1 equivalent1_2 equivalent2_1 equivalent2_2 different1_1 different1_2 different2_1 different2_2 main_has_in_between func_call eval1 eval2 eval3

equivalent1_1:
	gcc equivalent1_1.c -o equivalent1_1

equivalent1_2:
	gcc equivalent1_2.c -o equivalent1_2

equivalent2_1:
	gcc equivalent2_1.c -o equivalent2_1

equivalent2_2:
	gcc equivalent2_2.c -o equivalent2_2

different1_1:
	gcc different1_1.c -o different1_1

different1_2:
	gcc different1_2.c -o different1_2

different2_1:
	gcc different2_1.c -o different2_1

different2_2:
	gcc different2_2.c -o different2_2

func_call:
	gcc func_call.c -o func_call

main_has_in_between:
	gcc main_has_in_between.c -o main_has_in_between

eval1:
	gcc eval1.c -o eval1

eval2:
	gcc eval2.c -o eval2

eval3:
	gcc eval3.c -o eval3

clean:
	rm equivalent1_1 equivalent1_2 equivalent2_1 equivalent2_2 different1_1 different1_2 different2_1 different2_2 main_has_in_between func_call eval1 eval2 eval3